#spring.application.name=MigrateJiraBackend
#
#server.port=8085
#
## ── Jira Auth ────────────────────────────────────────────────
#jira.email=seemanki.aggarwal@ocr-inc.com
#jira.api-token=ATATT3xFfGF0gVe6OcDlmrMOWBwNCEvBGYiy-MSUnM68eCFzH8jrN9kUmtrEGsEAjeI6D5vTO86dauYhbPoQNa8JsysOB_VB1BXiOxrmYvTMSdt2uCA77pb2AS2kC8EDVW-Mto2D0VEA3WrUb-axtg-iRT6-rkyhDS7AQFyRRk3zSC8cBQ1wqpw=C2E76F0B
#
## ── File Paths ───────────────────────────────────────────────
#jira.csv-path=Jira-Dump.csv
#jira.download-dir=attachments_temp
#
## ── Download Settings ────────────────────────────────────────
## Parallel threads for downloading 
#jira.download-threads=10
#
## Skip already downloaded files 
#jira.skip-existing=true
#
#jira.request-delay-ms=100
#
## Timeout in seconds for each file download
#jira.timeout-seconds=60
#jira.test-limit=0
app.mode=import
#spring.datasource.url=jdbc:mysql://localhost:3306/jira_migrationDB
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#










spring.application.name=MigrateJiraBackend

server.port=${PORT:8085}

# ── Jira Auth ────────────────────────────────────────────────
jira.email=seemanki.aggarwal@ocr-inc.com
jira.api-token=ATATT3xFfGF0gVe6OcDlmrMOWBwNCEvBGYiy-MSUnM68eCFzH8jrN9kUmtrEGsEAjeI6D5vTO86dauYhbPoQNa8JsysOB_VB1BXiOxrmYvTMSdt2uCA77pb2AS2kC8EDVW-Mto2D0VEA3WrUb-axtg-iRT6-rkyhDS7AQFyRRk3zSC8cBQ1wqpw=C2E76F0B

# ── File Paths ───────────────────────────────────────────────
jira.csv-path=Jira-Dump.csv
jira.download-dir=attachments_temp



# ── Database — Aiven MySQL ───────────────────────────────────
spring.datasource.url=jdbc:mysql://mysql-2e407843-cryptotrade.h.aivencloud.com:11848/defaultdb?sslMode=REQUIRED&useSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_nDAoW9mmpVGpbF4c-yR
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false



